const words = [
  // ---------- 1a media ----------
  // SCHOOL
  { categories: ["SCHOOL", "NOUN"],  word: "art",          definition: "A school subject where you draw and paint.",                       classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "backpack",     definition: "A bag you carry on your back.",                                    classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "board",        definition: "The big surface where the teacher writes in class.",               classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "chair",        definition: "You sit on this at a table or desk.",                              classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "class",        definition: "A group of students who study together.",                          classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "desk",         definition: "A table where you work or study.",                                classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "geography",    definition: "A school subject about countries, maps and places.",              classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "glue",         definition: "A sticky thing that joins paper together.",                       classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "history",      definition: "A school subject about the past.",                                classe: "1media" },

  // FAM
  { categories: ["FAM", "NOUN"],     word: "aunt",         definition: "The sister of your mother or father.",                             classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "baby",         definition: "A very young child.",                                              classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "brother",      definition: "A boy who has the same parents as you.",                           classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "cousin",       definition: "The child of your aunt or uncle.",                                classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "father",       definition: "The man who is your parent.",                                     classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "grandfather",  definition: "The father of your mother or father.",                            classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "grandmother",  definition: "The mother of your mother or father.",                            classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "mother",       definition: "The woman who is your parent.",                                   classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "uncle",        definition: "The brother of your mother or father.",                           classe: "1media" },

  // ANIMAL
  { categories: ["ANIMAL", "NOUN"],  word: "alligator",    definition: "A big green animal that lives in water and has many teeth.",       classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "bird",         definition: "An animal with wings that can fly.",                               classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "cat",          definition: "A small animal that says \"meow\".",                               classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "dog",          definition: "An animal that says \"woof\".",                                   classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "elephant",     definition: "A very big grey animal with a long trunk.",                        classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "fish",         definition: "An animal that lives in water and swims.",                         classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "horse",        definition: "A big animal that people can ride.",                              classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "lion",         definition: "A big wild cat, the \"king of the jungle\".",                     classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "mouse",        definition: "A very small animal that likes cheese.",                          classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "tiger",        definition: "A big orange and black wild cat.",                                classe: "1media" },

  // PERSONALITY
  { categories: ["PERSONALITY", "ADJ"], word: "brave",     definition: "Not afraid in a difficult situation.",                             classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "clumsy",    definition: "A person who often drops things or falls.",                        classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "hard-working", definition: "A person who studies or works a lot.",                         classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "kind",      definition: "A person who is nice and helps people.",                          classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "lazy",      definition: "A person who doesn't like working or studying.",                  classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "selfish",   definition: "A person who only thinks about themselves.",                      classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "serious",   definition: "A person who doesn't smile much and is not playful.",             classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "shy",       definition: "A person who is quiet and afraid to speak to people.",            classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "stressed",  definition: "Feeling very worried and under pressure.",                        classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "talkative", definition: "A person who likes speaking a lot.",                              classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "young",     definition: "A person who is not old.",                                        classe: "1media" },

  // HOBBY
  { categories: ["HOBBY", "NOUN"],   word: "book",         definition: "Many pages together that you read.",                               classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "cooking",      definition: "Making food in the kitchen.",                                      classe: "1media" },
  { categories: ["HOBBY", "ACTION"], word: "dance",        definition: "To move your body to music.",                                      classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "drawing",      definition: "Making a picture with a pencil or pen.",                          classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "films",        definition: "Stories you watch on TV or at the cinema.",                       classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "football",     definition: "A sport where you kick a ball and try to score goals.",           classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "guitar",       definition: "A musical instrument with strings.",                              classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "music",        definition: "Sounds with rhythm that you like to listen to.",                  classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "video games",  definition: "Games you play on a console, phone or computer.",                 classe: "1media" },

  // ACTION
  { categories: ["ACTION"],          word: "ask",          definition: "To say words to get information or a question.",                   classe: "1media" },
  { categories: ["ACTION"],          word: "drink",        definition: "To put water, juice or another liquid in your mouth.",            classe: "1media" },
  { categories: ["ACTION"],          word: "go",           definition: "To move from one place to another.",                              classe: "1media" },
  { categories: ["ACTION"],          word: "have lunch",   definition: "Eat a meal in the middle of the day.",                            classe: "1media" },
  { categories: ["ACTION"],          word: "help",         definition: "To do something so another person's work is easier.",             classe: "1media" },
  { categories: ["ACTION"],          word: "listen",       definition: "Use your ears to hear sounds or people.",                         classe: "1media" },
  { categories: ["ACTION"],          word: "love",         definition: "To like someone or something very, very much.",                   classe: "1media" },
  { categories: ["ACTION"],          word: "open",         definition: "To move a door, window or book so it is not closed.",             classe: "1media" },
  { categories: ["ACTION"],          word: "pay",          definition: "Give money when you buy something.",                              classe: "1media" },
  { categories: ["ACTION"],          word: "play",         definition: "Have fun with a game or toy.",                                    classe: "1media" },
  { categories: ["ACTION"],          word: "run",          definition: "To move faster than walking.",                                    classe: "1media" },
  { categories: ["ACTION"],          word: "sleep",        definition: "To rest at night with your eyes closed.",                         classe: "1media" },
  { categories: ["ACTION"],          word: "speak",        definition: "To say words with your mouth.",                                   classe: "1media" },
  { categories: ["ACTION"],          word: "take",         definition: "To pick something up and hold or move it.",                       classe: "1media" },
  { categories: ["ACTION"],          word: "wake up",      definition: "Stop sleeping and open your eyes.",                               classe: "1media" },
  { categories: ["ACTION"],          word: "walk",         definition: "To move on your feet, not fast.",                                 classe: "1media" },

  // LIT
  { categories: ["LIT"],             word: "Alice",        definition: "A curious girl from a famous story.",                               classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "drug",         definition: "A strong medicine or illegal chemical people take.",               classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "maths",        definition: "A school subject with numbers and calculations.",                 classe: "1media" },
  { categories: ["LIT"],             word: "Marx",         definition: "A famous thinker about workers and politics.",                    classe: "1media" },
  { categories: ["LIT"],             word: "rabbit hole",  definition: "A deep hole where a rabbit lives.",                               classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "religion",     definition: "Ideas about God and different beliefs.",                          classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "revolution",   definition: "A big change in government or society.",                          classe: "1media" },
  { categories: ["LIT"],             word: "Yayoy",        definition: "The name of an artist who draws dots.",                           classe: "1media" },
  
  // GREEK MYTHOLOGY
  { categories: ["LIT"],             word: "Persephone",   definition: "The greek queen of the Underworld.",                              classe: "1media" },
  { categories: ["LIT"],             word: "Zeus",         definition: "The king of the Greek gods who controls thunder and lightning.",  classe: "1media" },
  { categories: ["LIT"],             word: "Hera",         definition: "The queen of the gods and wife of Zeus.",                         classe: "1media" },
  { categories: ["LIT"],             word: "Poseidon",     definition: "The god of the sea and earthquakes.",                             classe: "1media" },
  { categories: ["LIT"],             word: "Hades",        definition: "The god of the Underworld and the dead.",                         classe: "1media" },
  { categories: ["LIT"],             word: "Athena",       definition: "The goddess of wisdom and war.",                                  classe: "1media" },
  { categories: ["LIT"],             word: "Apollo",       definition: "The god of the sun, music, and poetry.",                          classe: "1media" },
  { categories: ["LIT"],             word: "Artemis",      definition: "The goddess of hunting and the moon.",                            classe: "1media" },
  { categories: ["LIT"],             word: "Aphrodite",    definition: "The goddess of love and beauty.",                                 classe: "1media" },
  { categories: ["LIT"],             word: "Ares",         definition: "The god of war and violence.",                                    classe: "1media" },
  { categories: ["LIT"],             word: "Hermes",       definition: "The messenger god with winged sandals.",                          classe: "1media" },
  { categories: ["LIT"],             word: "Demeter",      definition: "The goddess of harvest and agriculture.",                         classe: "1media" },
  { categories: ["LIT"],             word: "Hephaestus",   definition: "The god of fire and blacksmiths.",                                classe: "1media" },
  { categories: ["LIT"],             word: "Dionysus",     definition: "The god of wine and celebration.",                                classe: "1media" },
  { categories: ["LIT"],             word: "Hercules",     definition: "A hero famous for his incredible strength.",                      classe: "1media" },
  { categories: ["LIT"],             word: "Odysseus",     definition: "A clever hero who took a long journey home.",                     classe: "1media" },
  { categories: ["LIT"],             word: "Achilles",     definition: "A great warrior with only one weak spot on his heel.",            classe: "1media" },
  { categories: ["LIT"],             word: "Medusa",       definition: "A monster with snakes for hair who turns people to stone.",       classe: "1media" },
  { categories: ["LIT"],             word: "Minotaur",     definition: "A creature with a human body and bull's head.",                   classe: "1media" },
  { categories: ["LIT"],             word: "Pegasus",      definition: "A magical horse with wings.",                                     classe: "1media" },
  { categories: ["LIT"],             word: "Cyclops",      definition: "A giant with only one eye in the middle of his forehead.",        classe: "1media" },
  { categories: ["LIT"],             word: "Prometheus",   definition: "The titan who gave fire to humans.",                              classe: "1media" },
  { categories: ["LIT"],             word: "Pandora",      definition: "The first woman who opened a box and released evil into the world.", classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "Mount Olympus", definition: "The mountain where the Greek gods live.",                        classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "Underworld",   definition: "The place where dead people go in Greek myths.",                  classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "oracle",       definition: "A person who can see the future and give prophecies.",            classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "labyrinth",    definition: "A complicated maze that is hard to escape from.",                 classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "titan",        definition: "A giant god from before Zeus became king.",                       classe: "1media" },
  { categories: ["LIT", "ADJ"],      word: "immortal",     definition: "Someone who lives forever and never dies.",                       classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "mortal",       definition: "A human who will die one day.",                                   classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "hero",         definition: "A brave person who does great things.",                           classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "monster",      definition: "A scary creature that is dangerous.",                             classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "quest",        definition: "A long and difficult journey to find something.",                 classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "sacrifice",    definition: "Giving up something important for the gods.",                     classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "throne",       definition: "The special chair where a king or god sits.",                     classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "temple",       definition: "A building where people worship gods.",                           classe: "1media" },
  { categories: ["LIT", "ADJ"],      word: "divine",       definition: "Related to gods or coming from gods.",                            classe: "1media" },
  { categories: ["LIT", "ADJ"],      word: "legendary",    definition: "So famous that everyone knows the story.",                        classe: "1media" },

  // JOB
  { categories: ["JOB", "NOUN"],     word: "cook",         definition: "The person who prepares food in a restaurant.",                    classe: "1media" },

  // NOUN (generic)
  { categories: ["NOUN"],            word: "clock",        definition: "An object that shows the time.",                                   classe: "1media" },
  { categories: ["NOUN"],            word: "door",         definition: "You open this to go in or out of a room.",                        classe: "1media" },
  { categories: ["NOUN"],            word: "floor",        definition: "The part of the room you walk on.",                               classe: "1media" },
  { categories: ["NOUN"],            word: "money",        definition: "Coins and notes that you use to buy things.",                    classe: "1media" },
  { categories: ["NOUN"],            word: "notebook",     definition: "A small book where you write notes.",                             classe: "1media" },
  { categories: ["NOUN"],            word: "pen",          definition: "You use it with ink to write.",                                   classe: "1media" },
  { categories: ["NOUN"],            word: "ruler",        definition: "A long, flat tool you use to measure or draw lines.",             classe: "1media" },
  { categories: ["NOUN"],            word: "schoolbag",    definition: "A bag where you carry books to school.",                          classe: "1media" },
  { categories: ["NOUN"],            word: "science",      definition: "A school subject about nature and experiments.",                  classe: "1media" },
  { categories: ["NOUN"],            word: "scissors",     definition: "A small tool with two blades to cut paper.",                      classe: "1media" },
  { categories: ["NOUN"],            word: "sharpener",    definition: "A small tool to make a pencil sharp.",                            classe: "1media" },
  { categories: ["NOUN"],            word: "wall",         definition: "The vertical part around a room.",                                classe: "1media" },
  { categories: ["NOUN"],            word: "window",       definition: "The glass part of a wall you can see through.",                   classe: "1media" },

  // ADJ
  { categories: ["ADJ"],             word: "high",         definition: "Not low; at a big level or far from the ground.",                 classe: "1media" },
  { categories: ["ADJ"],             word: "noisy",        definition: "Making a lot of loud sounds.",                                    classe: "1media" },

  // OTHER
  { categories: ["OTHER"],           word: "English",      definition: "The language you are studying now.",                              classe: "1media" },
  { categories: ["OTHER"],           word: "ms Fatigato",  definition: "The name of the best English teacher ;)",                         classe: "1media" },
  { categories: [ "NOUN"],   word: "neighbor",     definition: "A person who lives near your house.",                             classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "P.E.",         definition: "A school subject where you do sport and exercise.",               classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "schizophrenia", definition: "A serious mental illness of the brain.",                    classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "sister",       definition: "A girl who has the same parents as you.",                         classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "student",      definition: "A person who goes to school to learn.",                           classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "teacher",      definition: "A person who helps students learn.",                              classe: "1media" },

  // EMOTION 
  { categories: ["EMOTION", "ADJ"],  word: "happy",        definition: "Feeling good and full of joy.",                                   classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "sad",          definition: "Feeling unhappy and wanting to cry.",                             classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "angry",        definition: "Feeling mad when something is wrong or unfair.",                  classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "scared",       definition: "Feeling afraid of something dangerous or unknown.",               classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "excited",      definition: "Feeling very happy about something that will happen.",            classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "worried",      definition: "Feeling nervous that something bad might happen.",                classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "surprised",    definition: "Feeling shocked because something unexpected happened.",          classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "lonely",       definition: "Feeling sad because you are alone.",                              classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "proud",        definition: "Feeling good about something you or someone else did.",           classe: "1media" },
  { categories: ["EMOTION", "ADJ"],  word: "jealous",      definition: "Feeling bad because someone has something you want.",             classe: "1media" },
  { categories: ["EMOTION", "NOUN"], word: "fear",         definition: "The feeling you have when you are scared.",                       classe: "1media" },
  { categories: ["EMOTION", "NOUN"], word: "joy",          definition: "A strong feeling of happiness.",                                  classe: "1media" },
  { categories: ["EMOTION", "NOUN"], word: "love",         definition: "A very strong feeling of caring about someone.",                  classe: "1media" },
  { categories: ["EMOTION", "NOUN"], word: "hate",         definition: "A very strong feeling of not liking someone or something.",       classe: "1media" },
  { categories: ["EMOTION", "ACTION"], word: "cry",        definition: "To let tears fall from your eyes when you are sad.",              classe: "1media" },
  { categories: ["EMOTION", "ACTION"], word: "laugh",      definition: "To make sounds when something is funny.",                         classe: "1media" },
  { categories: ["EMOTION", "ACTION"], word: "smile",      definition: "To move your mouth up when you are happy.",                       classe: "1media" },
  { categories: ["EMOTION", "ACTION"], word: "scream",     definition: "To make a loud sound when you are scared or angry.",              classe: "1media" },

  // ---------- 2a media ----------
  // CLOTHES
  { categories: ["CLOTHES", "ADJ"],  word: "baggy",        definition: "Clothes that are very wide and loose.",                           classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "coat",         definition: "A long warm jacket for cold weather.",                            classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "hoodie",       definition: "A warm top with a hood for your head.",                           classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "jacket",       definition: "A short coat you wear outside.",                                  classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "leather",      definition: "Material from animal skin for shoes or jackets.",                 classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "plain",        definition: "With one color and no picture.",                                  classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "shirt",        definition: "A piece of clothing with sleeves and buttons.",                   classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "skirt",        definition: "Clothing for the lower body that is open at the bottom.",         classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "striped",      definition: "With many lines in different colors.",                            classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "sweater",      definition: "A warm top you wear in winter.",                                  classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "tight",        definition: "Clothes that are very narrow on the body.",                       classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "trainers",     definition: "Comfortable shoes for sport or walking.",                         classe: "2media" },

  // LIT - Romeo and Juliet / Shakespeare
  { categories: ["LIT"],             word: "Shakespeare",  definition: "A famous English writer who wrote plays and poems.",              classe: "2media" },
  { categories: ["LIT"],             word: "Romeo",        definition: "The young man who falls in love with Juliet.",                    classe: "2media" },
  { categories: ["LIT"],             word: "Juliet",       definition: "The young girl who falls in love with Romeo.",                    classe: "2media" },
  { categories: ["LIT"],             word: "Montague",     definition: "Romeo's family name in the play.",                                classe: "2media" },
  { categories: ["LIT"],             word: "Capulet",      definition: "Juliet's family name in the play.",                               classe: "2media" },
  { categories: ["LIT"],             word: "Mercutio",     definition: "Romeo's best friend who dies in a fight.",                        classe: "2media" },
  { categories: ["LIT"],             word: "Tybalt",       definition: "Juliet's cousin who fights with Romeo.",                          classe: "2media" },
  { categories: ["LIT"],             word: "Friar Lawrence", definition: "The priest who helps Romeo and Juliet.",                        classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "balcony",      definition: "The place where Juliet stands when Romeo talks to her.",          classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "poison",       definition: "A dangerous liquid that can kill you.",                           classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "dagger",       definition: "A small knife used as a weapon.",                                 classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "feud",         definition: "A long fight between two families or groups.",                    classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "tragedy",      definition: "A sad story that ends badly.",                                    classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "tomb",         definition: "A place where dead people are buried.",                           classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "marriage",     definition: "When two people become husband and wife.",                        classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "secret",       definition: "Something you don't tell other people.",                          classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "fate",         definition: "The idea that things happen because they are meant to happen.",   classe: "2media" },
  { categories: ["LIT", "NOUN"],     word: "death",        definition: "When someone stops living.",                                      classe: "2media" },

  // ACTION (irregular verbs - 2media)
  { categories: ["ACTION"],          word: "blow",         definition: "To move air from your mouth or when the wind moves strongly.",    classe: "2media" },
  { categories: ["ACTION"],          word: "break",        definition: "To damage something so it is in pieces or does not work.",        classe: "2media" },
  { categories: ["ACTION"],          word: "bring",        definition: "To take something or someone with you to another place.",         classe: "2media" },
  { categories: ["ACTION"],          word: "build",        definition: "To make a house, bridge, or other structure.",                    classe: "2media" },
  { categories: ["ACTION", "SPORT"], word: "catch",        definition: "To take something that is moving through the air with your hands.", classe: "2media" },
  { categories: ["ACTION"],          word: "choose",       definition: "To decide which thing or person you want.",                       classe: "2media" },
  { categories: ["ACTION", "HOBBY"], word: "draw",         definition: "To make a picture with a pencil or pen.",                         classe: "2media" },
  { categories: ["ACTION"],          word: "drink",        definition: "To put water, juice or another liquid in your mouth.",            classe: "2media" },
  { categories: ["ACTION"],          word: "drive",        definition: "To control and move a car, bus, or other vehicle.",               classe: "2media" },
  { categories: ["ACTION"],          word: "eat",          definition: "To put food in your mouth and swallow it.",                       classe: "2media" },
  { categories: ["ACTION"],          word: "fall",         definition: "To go down to the ground by accident.",                           classe: "2media" },
  { categories: ["ACTION", "EMOTION"],word: "feel",        definition: "To experience a feeling like happy, sad, hot or cold.",           classe: "2media" },
  { categories: ["ACTION"],          word: "forget",       definition: "To not remember something.",                                      classe: "2media" },
  { categories: ["ACTION"],          word: "give",         definition: "To let someone have something.",                                  classe: "2media" },
  { categories: ["ACTION"],          word: "grow",         definition: "To become bigger or taller.",                                     classe: "2media" },
  { categories: ["ACTION"],          word: "hear",         definition: "To notice sounds with your ears.",                                classe: "2media" },
  { categories: ["ACTION"],          word: "hit",          definition: "To touch someone or something hard with your hand or an object.", classe: "2media" },
  { categories: ["ACTION"],          word: "keep",         definition: "To have something and not give or throw it away.",                classe: "2media" },
  { categories: ["ACTION"],          word: "know",         definition: "To have information or facts in your mind.",                      classe: "2media" },
  { categories: ["ACTION"],          word: "leave",        definition: "To go away from a place.",                                        classe: "2media" },
  { categories: ["ACTION"],          word: "make",         definition: "To create or produce something.",                                 classe: "2media" },
  { categories: ["ACTION"],          word: "meet",         definition: "To see and talk to someone, often for the first time.",           classe: "2media" },
  { categories: ["ACTION"],          word: "put",          definition: "To move something to a place and leave it there.",                classe: "2media" },
  { categories: ["ACTION", "HOBBY"], word: "read",         definition: "To look at words in a book and understand them.",                 classe: "2media" },
  { categories: ["ACTION", "HOBBY"], word: "ride",         definition: "To sit on a bike, horse, or motorbike and make it move.",         classe: "2media" },
  { categories: ["ACTION"],          word: "sell",         definition: "To give something to someone and get money.",                     classe: "2media" },
  { categories: ["ACTION"],          word: "send",         definition: "To make something go to another place or person.",                classe: "2media" },
  { categories: ["ACTION"],          word: "sit",          definition: "To rest your body on a chair or the floor.",                      classe: "2media" },
  { categories: ["ACTION"],          word: "sleep",        definition: "To rest with your eyes closed, usually at night.",                classe: "2media" },
  { categories: ["ACTION"],          word: "speak",        definition: "To say words with your mouth.",                                   classe: "2media" },
  { categories: ["ACTION"],          word: "spend",        definition: "To use time or money.",                                           classe: "2media" },
  { categories: ["ACTION", "HOBBY"], word: "swim",         definition: "To move through water using your arms and legs.",                 classe: "2media" },
  { categories: ["ACTION"],          word: "take",         definition: "To pick something up and hold or move it.",                       classe: "2media" },
  { categories: ["ACTION"],          word: "tell",         definition: "To say something to someone.",                                    classe: "2media" },
  { categories: ["ACTION", "SPORT"], word: "throw",        definition: "To make something fly through the air with your hand.",           classe: "2media" },
  { categories: ["ACTION"],          word: "understand",   definition: "To know what something means.",                                   classe: "2media" },
  { categories: ["ACTION", "HOBBY"], word: "write",        definition: "To put words or letters on paper or a screen.",                   classe: "2media" },

  // ---------- 3a media ----------
  // LIT
  { categories: ["LIT"],             word: "1984",         definition: "Orwell's novel about a totalitarian society and surveillance.",   classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "ambition",     definition: "A strong desire to achieve power or success.",                    classe: "3media" },
  { categories: ["LIT"],             word: "Animal Farm",  definition: "Orwell's novel about farm animals who rebel against humans.",     classe: "3media" },
  { categories: ["LIT"],             word: "Banquo",       definition: "Macbeth's friend and fellow general who is killed by Macbeth.",   classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "Big Brother",  definition: "The leader who watches everyone in Orwell's 1984.",               classe: "3media" },
  { categories: ["LIT"],             word: "Lady Macbeth", definition: "Macbeth's ambitious wife who persuades him to kill the king.",    classe: "3media" },
  { categories: ["LIT"],             word: "Macbeth",      definition: "Protagonist of a tragedy who wants to become king",               classe: "3media" },
  { categories: ["LIT"],             word: "Orwell",       definition: "A British writer famous for his political novels.",               classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "prophecy",     definition: "A prediction about what will happen in the future.",              classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "totalitarianism", definition: "A system where the government controls everything.",           classe: "3media" },
  { categories: ["LIT"],             word: "witch",        definition: "A magical woman who can cast spells and make potions",            classe: "3media" },

  // JOB
  { categories: ["JOB", "NOUN"],     word: "ACCOUNTANT",   definition: "A person who works with money and helps companies with their finances.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ACTOR",        definition: "A person who plays roles in movies, TV shows, or on stage.",      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ARCHITECT",    definition: "A person who designs buildings and houses.",                      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ARTIST",       definition: "A person who creates paintings, drawings, or other works of art.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "BAKER",        definition: "A person who makes bread, cakes, and pastries.",                  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "CARPENTER",    definition: "A person who makes or repairs things from wood.",                 classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "CHEF",         definition: "A person who cooks food in a restaurant or hotel.",               classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DENTIST",      definition: "A person who takes care of people's teeth.",                      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DESIGNER",     definition: "A person who creates plans or drawings for clothes, websites, or objects.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DOCTOR",       definition: "A person who helps sick or injured people get better.",           classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DRIVER",       definition: "A person who drives a car, bus, or truck.",                       classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ELECTRICIAN",  definition: "A person who installs or repairs electrical systems.",            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ENGINEER",     definition: "A person who designs or builds machines, buildings, or roads.",   classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FARMER",       definition: "A person who works on a farm growing plants or raising animals.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FILMMAKER",    definition: "A person who makes movies or videos.",                            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FIREMAN",      definition: "A person who stops fires and helps people in danger.",            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "GRAPHIC DESIGNER", definition: "A person who creates images and layouts for books, ads, or websites.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "HAIRDRESSER",  definition: "A person who cuts and styles hair.",                              classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "JOURNALIST",   definition: "A person who writes news stories for newspapers, TV, or online.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "LAWYER",       definition: "A person who helps people with legal problems.",                  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "MECHANIC",     definition: "A person who repairs cars or machines.",                          classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "MUSICIAN",     definition: "A person who plays a musical instrument or writes music.",        classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "PHOTOGRAPHER", definition: "A person who takes photos as a job.",                             classe: "3media" },
];
