const words = [
  // ---------- 1a media ----------
  { categories: ["LIT"],             word: "Alice",        definition: "A curious girl from a famous story.",                               classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "alligator",    definition: "A big green animal that lives in water and has many teeth.",       classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "art",          definition: "A school subject where you draw and paint.",                       classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "ask",          definition: "To say words to get information or a question.",                   classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "aunt",         definition: "The sister of your mother or father.",                             classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "baby",         definition: "A very young child.",                                              classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "backpack",     definition: "A bag you carry on your back.",                                    classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "bird",         definition: "An animal with wings that can fly.",                               classe: "1media" },
  { categories: ["SCHOOL", "NOUN"],  word: "board",        definition: "The big surface where the teacher writes in class.",               classe: "1media" },
  { categories: ["NOUN"],            word: "book",         definition: "Many pages together that you read.",                               classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "brave",     definition: "Not afraid in a difficult situation.",                             classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "brother",      definition: "A boy who has the same parents as you.",                           classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "cat",          definition: "A small animal that says \"meow\".",                               classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "chair",        definition: "You sit on this at a table or desk.",                              classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "class",        definition: "A group of students who study together.",                          classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "clock",        definition: "An object that shows the time.",                                   classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "clumsy",    definition: "A person who often drops things or falls.",                        classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "coat",         definition: "A warm piece of clothing you wear outside.",                       classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "cook",         definition: "The person who prepares food in a restaurant.",                    classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "cooking",      definition: "Making food in the kitchen.",                                      classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "cousin",       definition: "The child of your aunt or uncle.",                                classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "dance",        definition: "To move your body to music.",                                      classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "desk",         definition: "A table where you work or study.",                                classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "dog",          definition: "An animal that says \"woof\".",                                   classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "door",         definition: "You open this to go in or out of a room.",                        classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "drawing",      definition: "Making a picture with a pencil or pen.",                          classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "drink",        definition: "To put water, juice or another liquid in your mouth.",            classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "drug",         definition: "A strong medicine or illegal chemical people take.",               classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "elephant",     definition: "A very big grey animal with a long trunk.",                        classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "English",      definition: "The language you are studying now.",                              classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "father",       definition: "The man who is your parent.",                                     classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "films",        definition: "Stories you watch on TV or at the cinema.",                       classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "fish",         definition: "An animal that lives in water and swims.",                         classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "floor",        definition: "The part of the room you walk on.",                               classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "football",     definition: "A sport where you kick a ball and try to score goals.",           classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "geography",    definition: "A school subject about countries, maps and places.",              classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "glue",         definition: "A sticky thing that joins paper together.",                       classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "go",           definition: "To move from one place to another.",                              classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "grandfather",  definition: "The father of your mother or father.",                            classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "grandmother",  definition: "The mother of your mother or father.",                            classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "guitar",       definition: "A musical instrument with strings.",                              classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "hard-working", definition: "A person who studies or works a lot.",                         classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "have lunch",   definition: "Eat a meal in the middle of the day.",                            classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "help",         definition: "To do something so another person's work is easier.",             classe: "1media" },
  { categories: ["ADJ", "ADJ"],      word: "high",         definition: "Not low; at a big level or far from the ground.",                 classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "history",      definition: "A school subject about the past.",                                classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "horse",        definition: "A big animal that people can ride.",                              classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "kind",      definition: "A person who is nice and helps people.",                          classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "lazy",      definition: "A person who doesn't like working or studying.",                  classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "lion",         definition: "A big wild cat, the \"king of the jungle\".",                     classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "listen",       definition: "Use your ears to hear sounds or people.",                         classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "love",         definition: "To like someone or something very, very much.",                   classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "maths",        definition: "A school subject with numbers and calculations.",                 classe: "1media" },
  { categories: ["LIT"],             word: "Marx",         definition: "A famous thinker about workers and politics.",                    classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "money",        definition: "Coins and notes that you use to buy things.",                    classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "mother",       definition: "The woman who is your parent.",                                   classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "mouse",        definition: "A very small animal that likes cheese.",                          classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "ms Fatigato",  definition: "The name of your teacher.",                                      classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "music",        definition: "Sounds with rhythm that you like to listen to.",                  classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "neighbor",     definition: "A person who lives near your house.",                             classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "noisy",     definition: "Making a lot of loud sounds.",                                    classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "notebook",     definition: "A small book where you write notes.",                             classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "open",         definition: "To move a door, window or book so it is not closed.",             classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "pay",          definition: "Give money when you buy something.",                              classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "P.E.",         definition: "A school subject where you do sport and exercise.",               classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "pen",          definition: "You use it with ink to write.",                                   classe: "1media" },
  { categories: ["LIT"],             word: "Persephone",   definition: "The greek queen of the Underworld.",                              classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "play",         definition: "Have fun with a game or toy.",                                    classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "rabbit hole",  definition: "A deep hole where a rabbit lives.",                               classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "read",         definition: "Look at words in a book and understand them.",                    classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "religion",     definition: "Ideas about God and different beliefs.",                          classe: "1media" },
  { categories: ["LIT", "NOUN"],     word: "revolution",   definition: "A big change in government or society.",                          classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "ruler",        definition: "A long, flat tool you use to measure or draw lines.",             classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "run",          definition: "To move faster than walking.",                                    classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "schoolbag",    definition: "A bag where you carry books to school.",                          classe: "1media" },
  { categories: ["NOUN"],            word: "science",      definition: "A school subject about nature and experiments.",                  classe: "1media" },
  { categories: ["OTHER", "LIT", "NOUN"], word: "schizophrenia", definition: "A serious mental illness of the brain.",                    classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "scissors",     definition: "A small tool with two blades to cut paper.",                      classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "selfish",   definition: "A person who only thinks about themselves.",                      classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "serious",   definition: "A person who doesn't smile much and is not playful.",             classe: "1media" },
  { categories: ["NOUN", "NOUN"],    word: "sharpener",    definition: "A small tool to make a pencil sharp.",                            classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "shy",       definition: "A person who is quiet and afraid to speak to people.",            classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "sister",       definition: "A girl who has the same parents as you.",                         classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "sleep",        definition: "To rest at night with your eyes closed.",                         classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "speak",        definition: "To say words with your mouth.",                                   classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "student",      definition: "A person who goes to school to learn.",                           classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "stressed",  definition: "Feeling very worried and under pressure.",                        classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "take",         definition: "To pick something up and hold or move it.",                       classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "talkative", definition: "A person who likes speaking a lot.",                              classe: "1media" },
  { categories: ["OTHER", "NOUN"],   word: "teacher",      definition: "A person who helps students learn.",                              classe: "1media" },
  { categories: ["ANIMAL", "NOUN"],  word: "tiger",        definition: "A big orange and black wild cat.",                                classe: "1media" },
  { categories: ["FAM", "NOUN"],     word: "uncle",        definition: "The brother of your mother or father.",                           classe: "1media" },
  { categories: ["HOBBY", "NOUN"],   word: "video games",  definition: "Games you play on a console, phone or computer.",                 classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "wake up",      definition: "Stop sleeping and open your eyes.",                               classe: "1media" },
  { categories: ["ACTION", "VERB"],  word: "walk",         definition: "To move on your feet, not fast.",                                 classe: "1media" },
  { categories: ["NOUN", "OBJECT"],  word: "wall",         definition: "The vertical part around a room.",                                classe: "1media" },
  { categories: ["NOUN", "OBJECT"],  word: "window",       definition: "The glass part of a wall you can see through.",                   classe: "1media" },
  { categories: ["PERSONALITY", "ADJ"], word: "young",     definition: "A person who is not old.",                                        classe: "1media" },
  { categories: ["LIT"],             word: "Yayoy",        definition: "The name of an artist who draws dots.",                           classe: "1media" },

  // ---------- 2a media ----------
  { categories: ["CLOTHES", "ADJ"],  word: "baggy",        definition: "Clothes that are very wide and loose.",                           classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "tight",        definition: "Clothes that are very narrow on the body.",                       classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "leather",      definition: "Material from animal skin for shoes or jackets.",                 classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "jacket",       definition: "A short coat you wear outside.",                                  classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "shirt",        definition: "A piece of clothing with sleeves and buttons.",                   classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "skirt",        definition: "Clothing for the lower body that is open at the bottom.",         classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "hoodie",       definition: "A warm top with a hood for your head.",                           classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "trainers",     definition: "Comfortable shoes for sport or walking.",                         classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "coat",         definition: "A long warm jacket for cold weather.",                            classe: "2media" },
  { categories: ["CLOTHES", "NOUN"], word: "sweater",      definition: "A warm top you wear in winter.",                                  classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "striped",      definition: "With many lines in different colors.",                            classe: "2media" },
  { categories: ["CLOTHES", "ADJ"],  word: "plain",        definition: "With one color and no picture.",                                  classe: "2media" },

  // ---------- 3a media ----------
  { categories: ["LIT"],             word: "Macbeth",      definition: "Protagonist of a tragedy who wants to become king",               classe: "3media" },
  { categories: ["LIT"],             word: "Lady Macbeth", definition: "Macbeth's ambitious wife who persuades him to kill the king.",    classe: "3media" },
  { categories: ["LIT"],             word: "Banquo",       definition: "Macbeth's friend and fellow general who is killed by Macbeth.",   classe: "3media" },
  { categories: ["LIT"],             word: "witch",        definition: "A magical woman who can cast spells and make potions",            classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "ambition",     definition: "A strong desire to achieve power or success.",                    classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "prophecy",     definition: "A prediction about what will happen in the future.",              classe: "3media" },
  { categories: ["LIT"],             word: "Orwell",       definition: "A British writer famous for his political novels.",               classe: "3media" },
  { categories: ["LIT"],             word: "Animal Farm",  definition: "Orwell's novel about farm animals who rebel against humans.",     classe: "3media" },
  { categories: ["LIT"],             word: "1984",         definition: "Orwell's novel about a totalitarian society and surveillance.",   classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "totalitarianism", definition: "A system where the government controls everything.",           classe: "3media" },
  { categories: ["LIT", "NOUN"],     word: "Big Brother",  definition: "The leader who watches everyone in Orwell's 1984.",               classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "Professor",    definition: "A person who helps students learn in a high-school or college.",  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DOCTOR",       definition: "A person who helps sick or injured people get better.",           classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ENGINEER",     definition: "A person who designs or builds machines, buildings, or roads.",   classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FIREMAN",      definition: "A person who stops fires and helps people in danger.",            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "POLICE OFFICER", definition: "A person who keeps people safe and makes sure the law is followed.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "CHEF",         definition: "A person who cooks food in a restaurant or hotel.",               classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FARMER",       definition: "A person who works on a farm growing plants or raising animals.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DRIVER",       definition: "A person who drives a car, bus, or truck.",                       classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ARTIST",       definition: "A person who creates paintings, drawings, or other works of art.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "WAITER",       definition: "A person who serves food and drinks to people in a restaurant.",  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "MECHANIC",     definition: "A person who repairs cars or machines.",                          classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "VET",          definition: "A person who helps and treats sick animals.",                     classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "SCIENTIST",    definition: "A person who studies things to learn more about the world.",      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ACTOR",        definition: "A person who plays roles in movies, TV shows, or on stage.",      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "BAKER",        definition: "A person who makes bread, cakes, and pastries.",                  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ARCHITECT",    definition: "A person who designs buildings and houses.",                      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "JOURNALIST",   definition: "A person who writes news stories for newspapers, TV, or online.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "PHOTOGRAPHER", definition: "A person who takes photos as a job.",                             classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "PROGRAMMER",   definition: "A person who writes computer software and apps.",                 classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DESIGNER",     definition: "A person who creates plans or drawings for clothes, websites, or objects.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "MUSICIAN",     definition: "A person who plays a musical instrument or writes music.",        classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "TRANSLATOR",   definition: "A person who changes words from one language to another.",        classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ELECTRICIAN",  definition: "A person who installs or repairs electrical systems.",            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "PLUMBER",      definition: "A person who fixes water pipes and bathrooms.",                   classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "CARPENTER",    definition: "A person who makes or repairs things from wood.",                 classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "ACCOUNTANT",   definition: "A person who works with money and helps companies with their finances.", classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "PILOT",        definition: "A person who flies airplanes.",                                   classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "DENTIST",      definition: "A person who takes care of people's teeth.",                      classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "LAWYER",       definition: "A person who helps people with legal problems.",                  classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "HAIRDRESSER",  definition: "A person who cuts and styles hair.",                              classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "FILMMAKER",    definition: "A person who makes movies or videos.",                            classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "SCULPTOR",     definition: "A person who makes art using stone, wood, or metal.",             classe: "3media" },
  { categories: ["JOB", "NOUN"],     word: "GRAPHIC DESIGNER", definition: "A person who creates images and layouts for books, ads, or websites.", classe: "3media" }
];